/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kütüphaneUygulaması;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author enesk
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    String posta, girisYapan;

    Connection con;
    Statement sta;
    ResultSet rs;

    public MainMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        button_kitapIşlem.setEnabled(false);
        button_oduncIslem.setEnabled(false);
        button_personelIslem.setEnabled(false);
        button_cikisYap.setVisible(false);
        lbl_girisCıkısInfo.setHorizontalAlignment((int) CENTER_ALIGNMENT);
        lbl_bilgi.setHorizontalAlignment((int) CENTER_ALIGNMENT);

//personel ekleme manual deneme**************************************
       // Personel p0 = new Personel("admin", "Enes", "KARALİ", "admin@hotmail.com", "123", "Admin", "5398391184");
        // Personel p1 = new Personel("acakar", "Ahmet", "ÇAKAR", "ahmetcakar@gmail.com", "456789123", "Yönetici", "5341234634");
        //Personel p2 = new Personel("ekarali", "Enes", "KARALİ", "eneskarali96@hotmail.com", "789987789", "Personel", "5453671243");
        //Kitap k = new Kitap("12312312312", "sadasdsa", "asdsad", "sadsad", "321");
        //Kisi ki = new Kisi("enes", "karali", "05398391184", "eneskarali96@hotmail.com", new ArrayList());
//*******************************************************************        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_baslik = new javax.swing.JLabel();
        txt_kullanıcıAdi = new javax.swing.JTextField();
        lbl_kullaniciAdi = new javax.swing.JLabel();
        lbl_sifre = new javax.swing.JLabel();
        button_kitapIşlem = new javax.swing.JButton();
        button_oduncIslem = new javax.swing.JButton();
        button_personelIslem = new javax.swing.JButton();
        button_girisYap = new javax.swing.JButton();
        txt_sifre = new javax.swing.JPasswordField();
        lbl_bilgi = new javax.swing.JLabel();
        lbl_girisCıkısInfo = new javax.swing.JLabel();
        button_cikisYap = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_baslik.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        lbl_baslik.setForeground(new java.awt.Color(153, 0, 0));
        lbl_baslik.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_baslik.setText("İşlem Yapacak Personel Bilgileri");

        lbl_kullaniciAdi.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        lbl_kullaniciAdi.setForeground(new java.awt.Color(51, 51, 51));
        lbl_kullaniciAdi.setText("K. Adı:");

        lbl_sifre.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        lbl_sifre.setForeground(new java.awt.Color(51, 51, 51));
        lbl_sifre.setText("Şifre:");

        button_kitapIşlem.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        button_kitapIşlem.setText("Kitap İşlemleri");
        button_kitapIşlem.setDefaultCapable(false);
        button_kitapIşlem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_kitapIşlemActionPerformed(evt);
            }
        });

        button_oduncIslem.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        button_oduncIslem.setText("Ödünç İşlemleri");
        button_oduncIslem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_oduncIslemActionPerformed(evt);
            }
        });

        button_personelIslem.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        button_personelIslem.setText("Personel İşlemleri");
        button_personelIslem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_personelIslemActionPerformed(evt);
            }
        });

        button_girisYap.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        button_girisYap.setText("Giriş Yap");
        button_girisYap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_girisYapActionPerformed(evt);
            }
        });

        txt_sifre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sifreActionPerformed(evt);
            }
        });

        lbl_bilgi.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        lbl_bilgi.setForeground(new java.awt.Color(153, 0, 0));
        lbl_bilgi.setText("Bir işlem yapabilmek için personel veya yönetici girişi yapmalısınız");

        lbl_girisCıkısInfo.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        lbl_girisCıkısInfo.setForeground(new java.awt.Color(20, 97, 22));

        button_cikisYap.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        button_cikisYap.setText("Çıkış Yap");
        button_cikisYap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cikisYapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(313, 313, 313)
                .addComponent(button_girisYap, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 169, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_kullanıcıAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_kullaniciAdi, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_sifre, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                            .addComponent(button_personelIslem, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                                            .addComponent(button_kitapIşlem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(button_oduncIslem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(txt_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(221, 221, 221))
                    .addComponent(lbl_girisCıkısInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(button_cikisYap, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(314, 314, 314))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl_bilgi, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(179, 179, 179))))
            .addComponent(lbl_baslik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {button_kitapIşlem, button_oduncIslem, button_personelIslem});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_baslik)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_kullanıcıAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_kullaniciAdi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_sifre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_girisYap)
                .addGap(27, 27, 27)
                .addComponent(lbl_girisCıkısInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(button_cikisYap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_bilgi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_kitapIşlem, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_oduncIslem, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_personelIslem, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {button_kitapIşlem, button_oduncIslem, button_personelIslem});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txt_kullanıcıAdi, txt_sifre});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_sifreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sifreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sifreActionPerformed

    private void button_girisYapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_girisYapActionPerformed
        // TODO add your handling code here:
        String password = String.valueOf(txt_sifre.getPassword());
        boolean bulunduMu = false;

        try {
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/Kütüphane", "admin", "admin");
            sta = con.createStatement();
            rs = sta.executeQuery("SELECT * FROM PERSONEL");
            while (rs.next()) {
                bulunduMu = false;
                String kAdi = rs.getString("KADI");
                String sifre = rs.getString("SİFRE");
                if (kAdi.equals(txt_kullanıcıAdi.getText()) && sifre.equals(password)) {
                    lbl_kullaniciAdi.setVisible(false);
                    txt_kullanıcıAdi.setVisible(false);
                    lbl_sifre.setVisible(false);    
                    txt_sifre.setVisible(false);
                    button_girisYap.setVisible(false);
                    button_cikisYap.setVisible(true);
                    lbl_bilgi.setText("Yapılacak İşlem Türünü Seçiniz");
                    lbl_girisCıkısInfo.setText("GİRİŞ YAPILDI");
                    lbl_girisCıkısInfo.setForeground(new Color(20, 97, 22));
                    txt_kullanıcıAdi.setText("");
                    txt_sifre.setText("");
                    lbl_baslik.setText("İşlem Yapacak Personel: " + rs.getString("ADI").toUpperCase() + " " + rs.getString("SOYADI").toUpperCase());
                    button_kitapIşlem.setEnabled(true);
                    button_oduncIslem.setEnabled(true);
                    button_personelIslem.setEnabled(true);
                    posta=rs.getString("POSTA");
                    girisYapan=rs.getString("KADI");
                    bulunduMu = true;
                    break;
                }
            }
            rs.close();
            sta.close();
            con.close();

        } catch (SQLException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
 /*       for (Personel personel : Personel.personeller) {
            bulunduMu = false;
            if (personel.kAdi.equals(txt_kullanıcıAdi.getText()) && personel.getSifre(personel).equals(password)) {
                personel.DogruGiris = true;
                lbl_kullaniciAdi.setVisible(false);
                txt_kullanıcıAdi.setVisible(false);
                lbl_sifre.setVisible(false);
                txt_sifre.setVisible(false);
                button_girisYap.setVisible(false);
                button_cikisYap.setVisible(true);
                lbl_bilgi.setText("Yapılacak İşlem Türünü Seçiniz");
                lbl_girisCıkısInfo.setText("GİRİŞ YAPILDI");
                lbl_girisCıkısInfo.setForeground(new Color(20, 97, 22));
                txt_kullanıcıAdi.setText("");
                txt_sifre.setText("");
                lbl_baslik.setText("İşlem Yapacak Personel: " + personel.adi.toUpperCase() + " " + personel.soyAdi.toUpperCase());
                button_kitapIşlem.setEnabled(true);
                button_oduncIslem.setEnabled(true);
                button_personelIslem.setEnabled(true);
                girisYapan = personel;
                bulunduMu = true;
                break;
            }
        }
        */
        if (bulunduMu == false) {
            lbl_girisCıkısInfo.setText("YANLIŞ KULLANICI ADI VEYA ŞİFRE!");
            lbl_girisCıkısInfo.setHorizontalAlignment((int) CENTER_ALIGNMENT);
            txt_kullanıcıAdi.setText("");
            txt_sifre.setText("");
            lbl_girisCıkısInfo.setForeground(Color.red);

        }
    }//GEN-LAST:event_button_girisYapActionPerformed

    private void button_personelIslemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_personelIslemActionPerformed
        // TODO add your handling code here:
        PersonelEkran p = new PersonelEkran(girisYapan, this,posta);
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_button_personelIslemActionPerformed

    private void button_cikisYapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cikisYapActionPerformed
        // TODO add your handling code here:
        lbl_kullaniciAdi.setVisible(true);
        txt_kullanıcıAdi.setVisible(true);
        lbl_sifre.setVisible(true);
        txt_sifre.setVisible(true);
        button_girisYap.setVisible(true);
        button_cikisYap.setVisible(false);
        lbl_bilgi.setText("Bir işlem yapabilmek için personel veya yönetici girişi yapmalısınız");
        lbl_girisCıkısInfo.setText("Başarıyla Çıkış Yapıldı!");
        lbl_girisCıkısInfo.setForeground(new Color(20, 97, 22));
        txt_kullanıcıAdi.setText("");
        txt_sifre.setText("");
        lbl_baslik.setText("İşlem Yapacak Personel Bilgileri");
        button_kitapIşlem.setEnabled(false);
        button_oduncIslem.setEnabled(false);
        button_personelIslem.setEnabled(false);
        girisYapan = null;
    }//GEN-LAST:event_button_cikisYapActionPerformed

    private void button_kitapIşlemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_kitapIşlemActionPerformed
        // TODO add your handling code here:
        KitapEkran kitapEkran = new KitapEkran(this);
        kitapEkran.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_button_kitapIşlemActionPerformed

    private void button_oduncIslemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_oduncIslemActionPerformed
        // TODO add your handling code here:
        OduncMain odunc = new OduncMain(this);
        odunc.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_button_oduncIslemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_cikisYap;
    private javax.swing.JButton button_girisYap;
    private javax.swing.JButton button_kitapIşlem;
    private javax.swing.JButton button_oduncIslem;
    private javax.swing.JButton button_personelIslem;
    private javax.swing.JLabel lbl_baslik;
    private javax.swing.JLabel lbl_bilgi;
    private javax.swing.JLabel lbl_girisCıkısInfo;
    private javax.swing.JLabel lbl_kullaniciAdi;
    private javax.swing.JLabel lbl_sifre;
    private javax.swing.JTextField txt_kullanıcıAdi;
    private javax.swing.JPasswordField txt_sifre;
    // End of variables declaration//GEN-END:variables

}
