/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kütüphaneUygulaması;

/**
 *
 * @author enesk
 */
public class OduncMain extends javax.swing.JFrame {

    /**
     * Creates new form OduncMain
     */
    
    MainMenu anaEkran;
    public OduncMain(MainMenu main) {
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        anaEkran=main;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        txt_barkodNo = new javax.swing.JTextField();
        txt_kitapAdi = new javax.swing.JTextField();
        txt_yazarAdi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        button_mainMenu = new javax.swing.JButton();
        button_OduncVer = new javax.swing.JButton();
        button_verilenler = new javax.swing.JButton();
        button_kitapİade = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        button_mainMenu1 = new javax.swing.JButton();
        button_kisiler = new javax.swing.JButton();

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Yeni Kişi Ekle");

        txt_barkodNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_barkodNoMouseClicked(evt);
            }
        });
        txt_barkodNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_barkodNoActionPerformed(evt);
            }
        });

        txt_kitapAdi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_kitapAdiMouseClicked(evt);
            }
        });

        txt_yazarAdi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_yazarAdiMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel9.setText("Tel No:");

        jLabel4.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel4.setText("Adı:");

        jLabel5.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel5.setText("Soyadı:");

        jButton2.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jButton2.setText("Ekle");

        button_mainMenu.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        button_mainMenu.setText("Anasayfa");
        button_mainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_mainMenuActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        button_OduncVer.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        button_OduncVer.setText("Kitap Ödünç Ver");
        button_OduncVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_OduncVerActionPerformed(evt);
            }
        });

        button_verilenler.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        button_verilenler.setText("Ödünç Verilen Kitaplar");
        button_verilenler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_verilenlerActionPerformed(evt);
            }
        });

        button_kitapİade.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        button_kitapİade.setText("Kitap İade");
        button_kitapİade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_kitapİadeActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Ödünç İşlemleri");

        button_mainMenu1.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        button_mainMenu1.setText("Anasayfa");
        button_mainMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_mainMenu1ActionPerformed(evt);
            }
        });

        button_kisiler.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        button_kisiler.setText("Ödünç Alacak Kişi İşlemleri (Yeni Kişi Ekleme)");
        button_kisiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_kisilerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button_mainMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(button_OduncVer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button_kisiler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button_kitapİade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button_verilenler, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(235, 235, 235)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(button_mainMenu1)
                .addGap(101, 101, 101)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_OduncVer, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(button_kisiler, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_kitapİade, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_verilenler, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {button_kisiler, button_verilenler});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_barkodNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_barkodNoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_barkodNoMouseClicked

    private void txt_barkodNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_barkodNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_barkodNoActionPerformed

    private void txt_kitapAdiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_kitapAdiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kitapAdiMouseClicked

    private void txt_yazarAdiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_yazarAdiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_yazarAdiMouseClicked

    private void button_kitapİadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_kitapİadeActionPerformed
        // TODO add your handling code here:
        iadeEkran ekran = new iadeEkran(anaEkran, this);
        ekran.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_button_kitapİadeActionPerformed

    private void button_mainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_mainMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_mainMenuActionPerformed

    private void button_mainMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_mainMenu1ActionPerformed
        // TODO add your handling code here:
        anaEkran.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_button_mainMenu1ActionPerformed

    private void button_OduncVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_OduncVerActionPerformed
        // TODO add your handling code here:
        OduncEkran odunc = new OduncEkran(anaEkran,this);
        odunc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_button_OduncVerActionPerformed

    private void button_kisilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_kisilerActionPerformed
        // TODO add your handling code here:
        KisiEkran kisiEkran = new KisiEkran(anaEkran, this);
        kisiEkran.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_button_kisilerActionPerformed

    private void button_verilenlerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_verilenlerActionPerformed
        // TODO add your handling code here:
        OduncListe oliste= new OduncListe(anaEkran, this);
        oliste.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_button_verilenlerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OduncMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OduncMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OduncMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OduncMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(new Runnable() {
            //public void run() {
                //new OduncMain().setVisible(true);
            //}
       // });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_OduncVer;
    private javax.swing.JButton button_kisiler;
    private javax.swing.JButton button_kitapİade;
    private javax.swing.JButton button_mainMenu;
    private javax.swing.JButton button_mainMenu1;
    private javax.swing.JButton button_verilenler;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txt_barkodNo;
    private javax.swing.JTextField txt_kitapAdi;
    private javax.swing.JTextField txt_yazarAdi;
    // End of variables declaration//GEN-END:variables
}
