/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kütüphaneUygulaması;

import java.util.List;
import java.util.Vector;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author enesk
 */
public class OduncListe extends javax.swing.JFrame {

    /**
     * Creates new form OduncListe
     */
    
    DefaultTableModel oduncTable = new DefaultTableModel(0, 0);
    String[] baslik = {"BARKOD NO","Kitap Adı","Kitabı Ödünç Alan Kişi","Son Teslim Tarihi"};
    
    MainMenu anaEkran;
    OduncMain oduncAnaEkran;
    
    public OduncListe(MainMenu main, OduncMain omain) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        anaEkran=main;
        oduncAnaEkran=omain;
        
        oduncTable.setColumnIdentifiers(baslik);
        table_oduncteKitap.setModel(oduncTable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        button_oduncİslem = new javax.swing.JButton();
        button_anasayfa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_oduncteKitap = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jRadioButton1.setText("Tümü");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jRadioButton2.setText("Teslim Süresinin Bitmesine 3 Gün Kalanlar");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jRadioButton3.setText("Süresi Sona Erenler");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        button_oduncİslem.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        button_oduncİslem.setText("Ödünç İşlemleri");
        button_oduncİslem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_oduncİslemActionPerformed(evt);
            }
        });

        button_anasayfa.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        button_anasayfa.setText("Anasayfa");
        button_anasayfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_anasayfaActionPerformed(evt);
            }
        });

        table_oduncteKitap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_oduncteKitap);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(button_anasayfa, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_oduncİslem, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 382, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_anasayfa)
                    .addComponent(button_oduncİslem))
                .addGap(128, 128, 128)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        listeTemizle();
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("asdPU");
    EntityManager em = emf.createEntityManager();
    
    Query q = em.createQuery("SELECT k FROM KiTaplar k");
    List<KiTaplar> kitaplar = q.getResultList();
    
        for (KiTaplar k : kitaplar) {
            if (k.getOdunctemi()==true) {
                   Vector data = new Vector();
                   data.add(k.getBarkodno());
                   data.add(k.getAdi());
                   data.add(k.getTeslim());
                   oduncTable.addRow(data);
            }
        }
//        for (Kitap kitap : Kitap.kitaplar) {
//            if (kitap.oduncteMi==true) {
//                Vector data = new Vector();
//                data.add(kitap.barkodNo);
//                data.add(kitap.adi);
//                data.add(kitap.kitapKimde.adi+" "+kitap.kitapKimde.soyAdi);
//                data.add(kitap.teslimTarihi);
//                oduncTable.addRow(data);
//            }
//        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        listeTemizle();
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("asdPU");
    EntityManager em = emf.createEntityManager();
    
    Query q = em.createQuery("SELECT k FROM KiTaplar k");
    List<KiTaplar> kitaplar = q.getResultList();
    
        for (KiTaplar k : kitaplar) {
            if (k.getOdunctemi()==true) {
                long teslim= k.getTeslimd().getTime();
            long alinis= k.getAlinisd().getTime();
            long kalanSüre=teslim-alinis;
            if (kalanSüre<259200000 && kalanSüre>0) {
                   Vector data = new Vector();
                   data.add(k.getBarkodno());
                   data.add(k.getAdi());
                   data.add(k.getTeslim());
                   oduncTable.addRow(data);
            }
            }
        }
        
        
//        for (Kitap kitap : Kitap.kitaplar) {
//            if (kitap.oduncteMi==true) {
//            long teslim= kitap.teslimTarihiD.getTime();
//            long alinis= kitap.alınısTarihiD.getTime();
//            long kalanSüre=teslim-alinis;
//                if (kalanSüre<259200000 && kalanSüre>0) {
//                   Vector data = new Vector();
//                   data.add(kitap.barkodNo);
//                   data.add(kitap.adi);
//                   data.add(kitap.teslimTarihi);
//                   oduncTable.addRow(data);
//            }
//            }
//        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        listeTemizle();
        
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("asdPU");
    EntityManager em = emf.createEntityManager();
    
    Query q = em.createQuery("SELECT k FROM KiTaplar k");
    List<KiTaplar> kitaplar = q.getResultList();
    
        for (KiTaplar k : kitaplar) {
            if (k.getOdunctemi()==true) {
                long teslim= k.getTeslimd().getTime();
            long alinis= k.getAlinisd().getTime();
            long kalanSüre=teslim-alinis;
            if (kalanSüre<=0) {
                   Vector data = new Vector();
                   data.add(k.getBarkodno());
                   data.add(k.getAdi());
                   data.add(k.getTeslim());
                   oduncTable.addRow(data);
            }
            }
        }


//        for (Kitap kitap : Kitap.kitaplar) {
//            if (kitap.oduncteMi==true) {
//            long teslim= kitap.teslimTarihiD.getTime();
//            long alinis= kitap.alınısTarihiD.getTime();
//            long kalanSüre=teslim-alinis;
//                if (kalanSüre<=0) {
//                   Vector data = new Vector();
//                   data.add(kitap.barkodNo);
//                   data.add(kitap.adi);
//                   data.add(kitap.teslimTarihi);
//                   oduncTable.addRow(data);
//            }
//            }
//        }
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void button_anasayfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_anasayfaActionPerformed
        // TODO add your handling code here:
        anaEkran.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_button_anasayfaActionPerformed

    private void button_oduncİslemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_oduncİslemActionPerformed
        // TODO add your handling code here:
        oduncAnaEkran.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_button_oduncİslemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OduncListe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OduncListe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OduncListe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OduncListe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      //  java.awt.EventQueue.invokeLater(new Runnable() {
           // public void run() {
             //   new OduncListe().setVisible(true);
            //}
       // });
    }
    
        void listeTemizle(){
        if (table_oduncteKitap.getRowCount() > 0) {
            int don = table_oduncteKitap.getRowCount() - 1;
            for (int i = don; i >= 0; i--) {
                oduncTable.removeRow(i);
            }
            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton button_anasayfa;
    private javax.swing.JButton button_oduncİslem;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_oduncteKitap;
    // End of variables declaration//GEN-END:variables
}
