/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kütüphaneUygulaması;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author enesk
 */
public class PersonelEkran extends javax.swing.JFrame {

    /**
     * Creates new form Personel
     *
     * @param girisYapan
     */
    String aktifPersonel, posta;
    MainMenu anaMenu;

    Connection con;
    Statement sta;
    PreparedStatement pre;
    ResultSet rs;

    public PersonelEkran(String girisYapanKadi, MainMenu geriDon, String gposta) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        aktifPersonel = girisYapanKadi;
        anaMenu = geriDon;
        posta = gposta;

        txt_ePosta.setText(posta);
        lbl_sifreDeğistirInfo.setHorizontalAlignment((int) CENTER_ALIGNMENT);
        lbl_ePostaDegisInfo.setHorizontalAlignment((int) CENTER_ALIGNMENT);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_eskiSifre = new javax.swing.JPasswordField();
        txt_yeniSifre = new javax.swing.JPasswordField();
        txt_yeniSifreTekrar = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txt_ePosta = new javax.swing.JTextField();
        lbl_ePosta = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        lbl_sifreDeğistirInfo = new javax.swing.JLabel();
        lbl_ePostaDegisInfo = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        button_yonetici = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("Personel Bilgisi İşlemleri");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Şifre Güncelle");

        jLabel3.setText("Eski Şifre:");

        jLabel4.setText("Yeni Şifre:");

        jLabel5.setText("Yeni Şifre Tekrar:");

        jButton1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton1.setText("Şifreyi Değiştir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("E-Posta Güncelle");

        lbl_ePosta.setText("E-Posta:");

        jButton2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton2.setText("E-Postayı Güncelle");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lbl_sifreDeğistirInfo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_sifreDeğistirInfo.setText(" ");
        lbl_sifreDeğistirInfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbl_ePostaDegisInfo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_ePostaDegisInfo.setText(" ");

        jToggleButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jToggleButton1.setText("Ana Menüye Dön");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        button_yonetici.setText("Yönetici İşlemleri");
        button_yonetici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_yoneticiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(lbl_ePosta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_ePosta)
                            .addComponent(txt_eskiSifre)
                            .addComponent(txt_yeniSifre)
                            .addComponent(txt_yeniSifreTekrar, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(73, 73, 73)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lbl_sifreDeğistirInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(78, 78, 78))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_ePostaDegisInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_yonetici, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))))
            .addGroup(layout.createSequentialGroup()
                .addGap(351, 351, 351)
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(jLabel1))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_sifreDeğistirInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_eskiSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_yeniSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_yeniSifreTekrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_ePosta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_ePosta)
                            .addComponent(jButton2))))
                .addComponent(lbl_ePostaDegisInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addComponent(button_yonetici, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/Kütüphane", "admin", "admin");
            pre = con.prepareStatement("UPDATE PERSONEL SET SİFRE=? WHERE KADI=? AND SİFRE=?");
            pre.setString(2, aktifPersonel);
            pre.setString(3, String.valueOf(txt_eskiSifre.getPassword()));
            if (String.valueOf(txt_yeniSifre.getPassword()).length() < 8) {
                lbl_sifreDeğistirInfo.setText("Şifre En Az 8 Karakter Olmalı");
                lbl_sifreDeğistirInfo.setForeground(Color.red);
            } else if (!String.valueOf(txt_yeniSifre.getPassword()).equals(String.valueOf(txt_yeniSifreTekrar.getPassword()))) {
                lbl_sifreDeğistirInfo.setText("Şifre Tekrarı Uyuşmuyor");
                lbl_sifreDeğistirInfo.setForeground(Color.RED);
                txt_yeniSifre.setText("");
                txt_yeniSifreTekrar.setText("");
            } else {
                pre.setString(1, String.valueOf(txt_yeniSifre.getPassword()));
                if (pre.executeUpdate() == 0) {
                    lbl_sifreDeğistirInfo.setText("Eski Şifre Yanlış Girildi");
                    lbl_sifreDeğistirInfo.setForeground(Color.red);
                    txt_eskiSifre.setText("");
                    txt_yeniSifre.setText("");
                    txt_yeniSifreTekrar.setText("");
                } else {
                    lbl_sifreDeğistirInfo.setText("Şifreniz Değiştirildi");
                    lbl_sifreDeğistirInfo.setForeground(new Color(20, 97, 22));
                    txt_eskiSifre.setText("");
                    txt_yeniSifre.setText("");
                    txt_yeniSifreTekrar.setText("");
                }
            }
            pre.close();
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(PersonelEkran.class.getName()).log(Level.SEVERE, null, ex);
        }
//        if (String.valueOf(txt_eskiSifre.getPassword()).equals(aktifPersonel.getSifre(aktifPersonel))) {
//            if (String.valueOf(txt_yeniSifre.getPassword()).length() < 8) {
//                lbl_sifreDeğistirInfo.setText("Şifre En Az 8 Karakter Olmalı");
//                lbl_sifreDeğistirInfo.setForeground(Color.red);
//            } else if (String.valueOf(txt_yeniSifre.getPassword()).equals(String.valueOf(txt_yeniSifreTekrar.getPassword()))) {
//                aktifPersonel.setSifre(aktifPersonel, String.valueOf(txt_yeniSifre.getPassword()));
//                lbl_sifreDeğistirInfo.setText("Şifreniz Değiştirildi");
//                lbl_sifreDeğistirInfo.setForeground(new Color(20, 97, 22));
//                txt_eskiSifre.setText("");
//                txt_yeniSifre.setText("");
//                txt_yeniSifreTekrar.setText("");
//            } else {
//                lbl_sifreDeğistirInfo.setText("Şifre Tekrarı Uyuşmuyor");
//                lbl_sifreDeğistirInfo.setForeground(Color.RED);
//                txt_yeniSifre.setText("");
//                txt_yeniSifreTekrar.setText("");
//            }
//        } else {
//            lbl_sifreDeğistirInfo.setText("Eski Şifre Yanlış Girildi");
//            lbl_sifreDeğistirInfo.setForeground(Color.red);
//            txt_eskiSifre.setText("");
//            txt_yeniSifre.setText("");
//            txt_yeniSifreTekrar.setText("");
//        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        boolean degissinMi = true;

        String ePostaDesen = "[\\w]+@[\\w]+\\.[\\w]+";
        String ePosta = txt_ePosta.getText();
        Pattern pattern = Pattern.compile(ePostaDesen);
        Matcher matcher = pattern.matcher(ePosta);

        if (!matcher.find() || ePosta.isEmpty() == true) {
            lbl_ePostaDegisInfo.setText("Geçerli Bir E-Posta Giriniz");
            lbl_sifreDeğistirInfo.setForeground(Color.RED);
            degissinMi = false;
        } else if (txt_ePosta.getText().equals(posta)) {
            lbl_ePostaDegisInfo.setText("Zaten Girdiğiniz E-posta Adresi Kayıtlı");
            lbl_ePostaDegisInfo.setForeground(Color.red);
            degissinMi = false;
        }

        if (degissinMi == true) {
            try {
                con = DriverManager.getConnection("jdbc:derby://localhost:1527/Kütüphane", "admin", "admin");
                pre = con.prepareStatement("UPDATE PERSONEL SET POSTA=? WHERE KADI=?");
                pre.setString(1, txt_ePosta.getText());
                pre.setString(2, aktifPersonel);
                pre.executeUpdate();
                pre.close();
                con.close();

            } catch (SQLException ex) {
                Logger.getLogger(PersonelEkran.class.getName()).log(Level.SEVERE, null, ex);
            }
            lbl_ePostaDegisInfo.setText("E-posta Değiştirildi");
            lbl_ePostaDegisInfo.setForeground(new Color(20, 97, 22));
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        anaMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void button_yoneticiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_yoneticiActionPerformed
        String mevki = "";
        try {
            // TODO add your handling code here:
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/Kütüphane", "admin", "admin");
            pre = con.prepareStatement("SELECT MEVKI FROM PERSONEL WHERE KADI=?");
            pre.setString(1, aktifPersonel);
            rs= pre.executeQuery();
            while(rs.next()){
                mevki=rs.getObject(1).toString();
            }
            con.close();
            pre.close();
            rs.close();

        } catch (SQLException ex) {
            Logger.getLogger(PersonelEkran.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (!mevki.equals("Yönetici")) {
            JOptionPane.showMessageDialog(null, "Bu Bölüme Yalnızca Yöneci Hesapları Erişebilir!", "UYARI!", JOptionPane.WARNING_MESSAGE);
        } else {
            YoneticiEkran y = new YoneticiEkran(aktifPersonel, this, anaMenu);
            y.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_button_yoneticiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonelEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonelEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonelEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonelEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(new Runnable() {
        //  public void run() {
        //new PersonelEkran().setVisible(true);
    }
    //});
    //}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_yonetici;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lbl_ePosta;
    private javax.swing.JLabel lbl_ePostaDegisInfo;
    private javax.swing.JLabel lbl_sifreDeğistirInfo;
    private javax.swing.JTextField txt_ePosta;
    private javax.swing.JPasswordField txt_eskiSifre;
    private javax.swing.JPasswordField txt_yeniSifre;
    private javax.swing.JPasswordField txt_yeniSifreTekrar;
    // End of variables declaration//GEN-END:variables

}
