/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kütüphaneUygulaması;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author enesk
 */
public class YoneticiEkran extends javax.swing.JFrame {

    /**
     * Creates new form YoneticiEkran
     *
     * @param girisYapan
     */
    String aktifPersonel;
    PersonelEkran PersonelE;
    MainMenu mainMenu;
    String degisecekPersonel, degisecekPersonelsoy;

    DefaultTableModel personelTable = new DefaultTableModel(0, 0);
    String[] baslik = {"Mevki", "Kullanıcı Adı", "Adı Ve Soyadı", "Mail Adresi"};

    Connection con;
    Statement sta;
    PreparedStatement pre;
    ResultSet rs;

    public YoneticiEkran(String girisYapanKadi, PersonelEkran pEkran, MainMenu anaMenu) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);

        aktifPersonel = girisYapanKadi;
        PersonelE = pEkran;
        mainMenu = anaMenu;

        button_personelDüzenle.setEnabled(false);
        button_personelSil.setEnabled(false);
        button_sifreSıfırla.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_kullaniciAdi = new javax.swing.JTextField();
        txt_adi = new javax.swing.JTextField();
        txt_soyAdi = new javax.swing.JTextField();
        txt_ePosta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        button_personelDon = new javax.swing.JButton();
        button_anaMenuDon = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_telNo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        button_personelEkle = new javax.swing.JButton();
        button_personelSil = new javax.swing.JButton();
        button_personelDüzenle = new javax.swing.JButton();
        button_sifreSıfırla = new javax.swing.JButton();
        button_personelListele = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_ara = new javax.swing.JTextField();
        button_ara = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_personelTablo = new javax.swing.JTable();
        button_temizle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_kullaniciAdi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_kullaniciAdiMouseClicked(evt);
            }
        });
        txt_kullaniciAdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kullaniciAdiActionPerformed(evt);
            }
        });
        txt_kullaniciAdi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_kullaniciAdiKeyPressed(evt);
            }
        });
        getContentPane().add(txt_kullaniciAdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 59, 224, 32));

        txt_adi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_adiMouseClicked(evt);
            }
        });
        txt_adi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_adiKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_adiKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_adiKeyTyped(evt);
            }
        });
        getContentPane().add(txt_adi, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 99, 224, 32));

        txt_soyAdi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_soyAdiMouseClicked(evt);
            }
        });
        txt_soyAdi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_soyAdiKeyPressed(evt);
            }
        });
        getContentPane().add(txt_soyAdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 139, 224, 32));

        txt_ePosta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_ePostaMouseClicked(evt);
            }
        });
        txt_ePosta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_ePostaKeyPressed(evt);
            }
        });
        getContentPane().add(txt_ePosta, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 179, 224, 32));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("Yönetici İşlemleri");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 10, -1, -1));

        button_personelDon.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        button_personelDon.setText("Personel İşlemleri");
        button_personelDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_personelDonActionPerformed(evt);
            }
        });
        getContentPane().add(button_personelDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 6, -1, -1));

        button_anaMenuDon.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        button_anaMenuDon.setText("Ana Menü");
        button_anaMenuDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_anaMenuDonActionPerformed(evt);
            }
        });
        getContentPane().add(button_anaMenuDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 133, -1));

        jLabel2.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel2.setText("K. Adı:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 68, -1, -1));

        jLabel3.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel3.setText("Adı:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 108, -1, -1));

        jLabel4.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel4.setText("Soyadı:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 148, -1, -1));

        jLabel5.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel5.setText("E-Posta:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 188, -1, -1));

        txt_telNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_telNoMouseClicked(evt);
            }
        });
        txt_telNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_telNoKeyPressed(evt);
            }
        });
        getContentPane().add(txt_telNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 219, 224, 32));

        jLabel6.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel6.setText("Tel No:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 228, -1, -1));

        button_personelEkle.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        button_personelEkle.setText("Personel Ekle");
        button_personelEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_personelEkleActionPerformed(evt);
            }
        });
        getContentPane().add(button_personelEkle, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 99, 199, 148));

        button_personelSil.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        button_personelSil.setText("Seçili Personeli Sil");
        button_personelSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_personelSilActionPerformed(evt);
            }
        });
        getContentPane().add(button_personelSil, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 99, 199, 71));

        button_personelDüzenle.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        button_personelDüzenle.setText("Personel Bilgilerini Güncelle");
        button_personelDüzenle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_personelDüzenleActionPerformed(evt);
            }
        });
        getContentPane().add(button_personelDüzenle, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 176, -1, 71));

        button_sifreSıfırla.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        button_sifreSıfırla.setText("Şifresini Sıfırla");
        button_sifreSıfırla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_sifreSıfırlaActionPerformed(evt);
            }
        });
        getContentPane().add(button_sifreSıfırla, new org.netbeans.lib.awtextra.AbsoluteConstraints(719, 99, 199, 71));

        button_personelListele.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        button_personelListele.setText("Tümünü Listele");
        button_personelListele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_personelListeleActionPerformed(evt);
            }
        });
        getContentPane().add(button_personelListele, new org.netbeans.lib.awtextra.AbsoluteConstraints(719, 176, 199, 71));

        jLabel7.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 0));
        jLabel7.setText("Personel Silme, Düzenleme Ve Şifre Sıfıflama İçin Bir Personel Seçilmeli");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 253, -1, 16));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Personel", "Yönetici" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 259, 224, -1));

        jLabel8.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel8.setText("Yetki:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 265, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Personel Ara");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, -1, -1));
        getContentPane().add(txt_ara, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 292, -1));

        button_ara.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        button_ara.setText("Ara");
        button_ara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_araActionPerformed(evt);
            }
        });
        getContentPane().add(button_ara, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, 143, -1));

        jLabel10.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel10.setText("Ad, Soyad, E-posta veya Tel No:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, -1));

        table_personelTablo.setAutoCreateColumnsFromModel(false);
        table_personelTablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_personelTablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_personelTabloMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_personelTablo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 396, 912, 130));

        button_temizle.setText("Dolu Alanları Temizle");
        button_temizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_temizleActionPerformed(evt);
            }
        });
        getContentPane().add(button_temizle, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 240, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_anaMenuDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_anaMenuDonActionPerformed
        // TODO add your handling code here:
        mainMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_button_anaMenuDonActionPerformed

    private void button_personelDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_personelDonActionPerformed
        // TODO add your handling code here:
        PersonelE.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_button_personelDonActionPerformed

    private void button_personelListeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_personelListeleActionPerformed
        // TODO add your handling code here:

        table_personelTablo.setAutoCreateColumnsFromModel(true);
        table_personelTablo.setAutoCreateRowSorter(true);

        personelTable.setColumnIdentifiers(baslik);
        table_personelTablo.setModel(personelTable);

        listeTemizle();

        listele();
    }//GEN-LAST:event_button_personelListeleActionPerformed

    private void button_araActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_araActionPerformed
        // TODO add your handling code here:

        table_personelTablo.setAutoCreateColumnsFromModel(true);
        table_personelTablo.setAutoCreateRowSorter(true);

        personelTable.setColumnIdentifiers(baslik);
        table_personelTablo.setModel(personelTable);

        listeTemizle();

        String ara = txt_ara.getText();

        try {
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/Kütüphane", "admin", "admin");
            sta = con.createStatement();
            rs = sta.executeQuery("SELECT * FROM PERSONEL");
            while (rs.next()) {
                if (ara.equals(rs.getString("ADI")) || ara.equals(rs.getString("SOYADI")) || ara.equals(rs.getString("POSTA")) || ara.equals(rs.getString("TELEFON"))) {
                    if (!aktifPersonel.equals(rs.getString("KADI"))) {
                        Vector<Object> data = new Vector<>();
                        data.add(rs.getString("MEVKI"));
                        data.add(rs.getString("KADI"));
                        data.add(rs.getString("ADI") + " " + rs.getString("SOYADI"));
                        data.add(rs.getString("POSTA"));
                        personelTable.addRow(data);
                        break;
                    }
                }
            }
            con.close();
            sta.close();
            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(YoneticiEkran.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_button_araActionPerformed

    private void button_personelEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_personelEkleActionPerformed
        // TODO add your handling code here:
        if (regexKontrol() == true && kayıtlıMıKontrol() == true) {
            Personel personel = new Personel(txt_kullaniciAdi.getText(), txt_adi.getText(), txt_soyAdi.getText(), txt_ePosta.getText(), "123" + txt_kullaniciAdi.getText(), jComboBox1.getSelectedItem().toString(), txt_telNo.getText());
            JOptionPane.showMessageDialog(null, txt_adi.getText() + " " + txt_soyAdi.getText() + " Yeni Personel Olarak Eklendi", "PERSONEL EKLENDİ", JOptionPane.INFORMATION_MESSAGE);
            txt_adi.setText("");
            txt_ara.setText("");
            txt_ePosta.setText("");
            txt_kullaniciAdi.setText("");
            txt_soyAdi.setText("");
            txt_telNo.setText("");
        }

    }//GEN-LAST:event_button_personelEkleActionPerformed

    private void button_personelSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_personelSilActionPerformed
        // TODO add your handling code here:
        int yesNo = JOptionPane.showConfirmDialog(this, degisecekPersonel + " " + degisecekPersonelsoy + " Silinsin Mi?", "Emin misin?", JOptionPane.YES_NO_OPTION);
        if (yesNo == 0) {
            try {
                con = DriverManager.getConnection("jdbc:derby://localhost:1527/Kütüphane", "admin", "admin");
                pre = con.prepareStatement("DELETE FROM PERSONEL WHERE KADI=?");
                pre.setString(1, degisecekPersonel);
                pre.executeUpdate();
                pre.close();
                con.close();
            } catch (SQLException ex) {
                Logger.getLogger(YoneticiEkran.class.getName()).log(Level.SEVERE, null, ex);
            }
            txt_adi.setText("");
            txt_ePosta.setText("");
            txt_kullaniciAdi.setText("");
            txt_soyAdi.setText("");
            txt_telNo.setText("");
            listeTemizle();
            listele();
        }
    }//GEN-LAST:event_button_personelSilActionPerformed

    private void txt_kullaniciAdiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_kullaniciAdiMouseClicked
        // TODO add your handling code here:
        if (txt_kullaniciAdi.getForeground() == Color.red) {
            txt_kullaniciAdi.setText("");
            txt_kullaniciAdi.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txt_kullaniciAdiMouseClicked

    private void txt_kullaniciAdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kullaniciAdiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kullaniciAdiActionPerformed

    private void txt_adiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_adiMouseClicked
        // TODO add your handling code here:
        if (txt_adi.getForeground() == Color.red) {
            txt_adi.setText("");
            txt_adi.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txt_adiMouseClicked

    private void txt_soyAdiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_soyAdiMouseClicked
        // TODO add your handling code here:
        if (txt_soyAdi.getForeground() == Color.red) {
            txt_soyAdi.setText("");
            txt_soyAdi.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txt_soyAdiMouseClicked

    private void txt_ePostaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_ePostaMouseClicked
        // TODO add your handling code here:
        if (txt_ePosta.getForeground() == Color.red) {
            txt_ePosta.setText("");
            txt_ePosta.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txt_ePostaMouseClicked

    private void txt_telNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_telNoMouseClicked
        // TODO add your handling code here:
        if (txt_telNo.getForeground() == Color.red) {
            txt_telNo.setText("");
            txt_telNo.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txt_telNoMouseClicked

    private void table_personelTabloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_personelTabloMouseClicked
        // TODO add your handling code here:

        txt_adi.setForeground(Color.BLACK);
        txt_ePosta.setForeground(Color.BLACK);
        txt_kullaniciAdi.setForeground(Color.BLACK);
        txt_soyAdi.setForeground(Color.BLACK);
        txt_telNo.setForeground(Color.BLACK);

        if (table_personelTablo.getSelectedRow() >= 0) {
            button_personelDüzenle.setEnabled(true);
            button_personelSil.setEnabled(true);
            button_sifreSıfırla.setEnabled(true);

            degisecekPersonel = table_personelTablo.getValueAt(table_personelTablo.getSelectedRow(), 1).toString();

            try {
                con = DriverManager.getConnection("jdbc:derby://localhost:1527/Kütüphane", "admin", "admin");
                sta = con.createStatement();

                rs = sta.executeQuery("SELECT * FROM PERSONEL");
                while (rs.next()) {
                    if (rs.getString("KADI").equals(degisecekPersonel)) {
                        degisecekPersonelsoy = rs.getString("SOYADI");
                        txt_adi.setText(rs.getString("ADI"));
                        txt_ePosta.setText(rs.getString("POSTA"));
                        txt_kullaniciAdi.setText(rs.getString("KADI"));
                        txt_soyAdi.setText(rs.getString("SOYADI"));
                        txt_telNo.setText(rs.getString("TELEFON"));
                        jComboBox1.setSelectedItem(rs.getString("MEVKI"));
                        break;
                    }
                }
                rs.close();
                sta.close();
                con.close();
            } catch (SQLException ex) {
                Logger.getLogger(YoneticiEkran.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_table_personelTabloMouseClicked

    private void button_temizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_temizleActionPerformed
        // TODO add your handling code here:
        txt_adi.setText("");
        txt_ePosta.setText("");
        txt_kullaniciAdi.setText("");
        txt_soyAdi.setText("");
        txt_telNo.setText("");
        listeTemizle();
    }//GEN-LAST:event_button_temizleActionPerformed

    private void button_personelDüzenleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_personelDüzenleActionPerformed
        // TODO add your handling code here: 
        boolean varMi = false;
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("asdPU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("SELECT p FROM Personel_1 p");
        List<Personel_1> personeller = q.getResultList();
        for (Personel_1 p : personeller) {
            if (!(p.getKadi().equals(degisecekPersonel))) {
                if (p.getKadi().equals(txt_kullaniciAdi.getText())) {
                    varMi=true;
                    break;
                }
            }
        }
        if (varMi==false && regexKontrol()==true) {
            q = em.createQuery("UPDATE Personel_1 p SET p.adi=:adi, p.kadi=:kadi, p.mevki=:mevki, p.posta=:posta, p.soyadi=:soyadi, p.telefon=:telefon  WHERE P.kadi=:kadiara");
            q.setParameter("adi", txt_adi.getText());
            q.setParameter("kadi", txt_kullaniciAdi.getText());
            q.setParameter("mevki", jComboBox1.getSelectedItem().toString());
            q.setParameter("posta", txt_ePosta.getText());
            q.setParameter("telefon", txt_telNo.getText());
            q.setParameter("soyadi", txt_soyAdi.getText());
            q.setParameter("kadiara", degisecekPersonel);
            em.getTransaction().begin(); 
            q.executeUpdate();
            em.getTransaction().commit();
            em.close();
            emf.close();
            JOptionPane.showMessageDialog(null, "Değişiklik Yapıldı", "Değiştirildi", JOptionPane.INFORMATION_MESSAGE); listeTemizle();
            listele();
            txt_adi.setText("");
            txt_ara.setText("");
            txt_ePosta.setText("");
            txt_kullaniciAdi.setText("");
            txt_soyAdi.setText("");
            txt_telNo.setText("");
        }
        else{
            JOptionPane.showMessageDialog(null, "Zaten Bu Kullanıcı Adı İle Kayıtlı Personel Var", "UYARI!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_button_personelDüzenleActionPerformed

    private void button_sifreSıfırlaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_sifreSıfırlaActionPerformed
        // TODO add your handling code here:y
        int yesNo = JOptionPane.showConfirmDialog(this, degisecekPersonel + " " + degisecekPersonelsoy + " Şifresi Default Şifre Olarak Sıfırlansın Mı?", "Emin misin?", JOptionPane.YES_NO_OPTION);
        if (yesNo == 0) {
            try {
                con = DriverManager.getConnection("jdbc:derby://localhost:1527/Kütüphane", "admin", "admin");
                pre = con.prepareCall("UPDATE FROM PERSONEL SET SİFRE=? WHERE KADI=?");
                pre.setString(1, "111" + degisecekPersonel);
                JOptionPane.showMessageDialog(null, "Kullanıcının Şifresi Sıfırlandı", "BİLGİ", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {
                Logger.getLogger(YoneticiEkran.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_button_sifreSıfırlaActionPerformed

    private void txt_kullaniciAdiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_kullaniciAdiKeyPressed
        // TODO add your handling code here:
        if (txt_kullaniciAdi.getForeground() == Color.red) {
            txt_kullaniciAdi.setText("");
            txt_kullaniciAdi.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txt_kullaniciAdiKeyPressed

    private void txt_adiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_adiKeyPressed
        // TODO add your handling code here:
        if (txt_adi.getForeground() == Color.red) {
            txt_adi.setText("");
            txt_adi.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txt_adiKeyPressed

    private void txt_adiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_adiKeyReleased

    }//GEN-LAST:event_txt_adiKeyReleased

    private void txt_adiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_adiKeyTyped

    }//GEN-LAST:event_txt_adiKeyTyped

    private void txt_soyAdiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_soyAdiKeyPressed
        // TODO add your handling code here:
        if (txt_soyAdi.getForeground() == Color.red) {
            txt_soyAdi.setText("");
            txt_soyAdi.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txt_soyAdiKeyPressed

    private void txt_ePostaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ePostaKeyPressed
        // TODO add your handling code here:
        if (txt_ePosta.getForeground() == Color.red) {
            txt_ePosta.setText("");
            txt_ePosta.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txt_ePostaKeyPressed

    private void txt_telNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telNoKeyPressed
        // TODO add your handling code here:
        if (txt_telNo.getForeground() == Color.red) {
            txt_telNo.setText("");
            txt_telNo.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txt_telNoKeyPressed

    boolean regexKontrol() {

        boolean eklensinMi = true;

        String kAdi = txt_kullaniciAdi.getText();
        String kAdiDesen = "[\\W\\d]";
        String ePostaDesen = "[\\w]+@[\\w]+\\.[\\w]+";
        String telNoDesen = "[\\d]{11}";
        Pattern pattern = Pattern.compile(kAdiDesen);
        Matcher matcher = pattern.matcher(kAdi);

        if (matcher.find() || kAdi.isEmpty() == true) {
            txt_kullaniciAdi.setText("Geçerli Bir Kullanıcı Adı Giriniz");
            txt_kullaniciAdi.setForeground(Color.red);
            eklensinMi = false;
        }

        String adi = txt_adi.getText();
        matcher = pattern.matcher(adi);

        if (matcher.find() || adi.isEmpty() == true) {
            txt_adi.setText("Geçerli Bir Ad Giriniz");
            txt_adi.setForeground(Color.red);
            eklensinMi = false;
        }

        String soyAdi = txt_soyAdi.getText();
        matcher = pattern.matcher(soyAdi);

        if (matcher.find() || soyAdi.isEmpty() == true) {
            txt_soyAdi.setText("Geçerli Bir Soyad Giriniz");
            txt_soyAdi.setForeground(Color.red);
            eklensinMi = false;
        }

        String ePosta = txt_ePosta.getText();
        pattern = Pattern.compile(ePostaDesen);
        matcher = pattern.matcher(ePosta);

        if (!matcher.find() || ePosta.isEmpty() == true) {
            txt_ePosta.setText("Geçerli Bir E-Posta Giriniz");
            txt_ePosta.setForeground(Color.red);
            eklensinMi = false;
        }

        String telNo = txt_telNo.getText();
        pattern = Pattern.compile(telNoDesen);
        matcher = pattern.matcher(telNo);

        if (!matcher.find() || telNo.isEmpty() == true) {
            txt_telNo.setText("Geçerli Bir Telefon Numarası Giriniz");
            txt_telNo.setForeground(Color.red);
            eklensinMi = false;
        }
        return eklensinMi;
    }

    boolean kayıtlıMıKontrol() {
        boolean eklensinMi = true;
        try {
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/Kütüphane", "admin", "admin");
            sta = con.createStatement();
            rs = sta.executeQuery("SELECT * FROM PERSONEL");
            while (rs.next()) {
                if (txt_kullaniciAdi.getText().equals(rs.getString("KADI"))) {
                    eklensinMi = false;
                    JOptionPane.showMessageDialog(null, "Girdiğiniz Kullanıcı Adı Zaten Farklı Bir Üye İçin Kayıtlı", "UYARI!", JOptionPane.WARNING_MESSAGE);
                    txt_ePosta.setText("");
                    txt_kullaniciAdi.setText("");
                    break;
                }
            }
            rs.close();
            sta.close();
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(YoneticiEkran.class.getName()).log(Level.SEVERE, null, ex);
        }
        return eklensinMi;
    }

    void listeTemizle() {

        if (table_personelTablo.getRowCount() > 0) {
            int don = table_personelTablo.getRowCount() - 1;
            for (int i = don; i >= 0; i--) {
                personelTable.removeRow(i);
            }
        }
    }

    void listele() {
        try {
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/Kütüphane", "admin", "admin");
            sta = con.createStatement();
            rs = sta.executeQuery("SELECT * FROM PERSONEL");
            while (rs.next()) {
                if (!rs.getString("KADI").equals(aktifPersonel)) {
                    Vector<Object> data = new Vector<>();
                    data.add(rs.getString("MEVKİ"));
                    data.add(rs.getString("KADI"));
                    data.add(rs.getString("ADI") + " "+rs.getString("SOYADI"));
                    data.add(rs.getString("POSTA"));
                    personelTable.addRow(data);
                }
            }
            rs.close();
            sta.close();
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(YoneticiEkran.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YoneticiEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YoneticiEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YoneticiEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YoneticiEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(new Runnable() {
        //public void run() {
        // new YoneticiEkran().setVisible(true);
        //}
        //});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_anaMenuDon;
    private javax.swing.JButton button_ara;
    private javax.swing.JButton button_personelDon;
    private javax.swing.JButton button_personelDüzenle;
    private javax.swing.JButton button_personelEkle;
    private javax.swing.JButton button_personelListele;
    private javax.swing.JButton button_personelSil;
    private javax.swing.JButton button_sifreSıfırla;
    private javax.swing.JButton button_temizle;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_personelTablo;
    private javax.swing.JTextField txt_adi;
    private javax.swing.JTextField txt_ara;
    private javax.swing.JTextField txt_ePosta;
    private javax.swing.JTextField txt_kullaniciAdi;
    private javax.swing.JTextField txt_soyAdi;
    private javax.swing.JTextField txt_telNo;
    // End of variables declaration//GEN-END:variables
}
